export const IMPACT_LEVELS = {
  off: null,
  low: {
    color: '#0d9488',
    duration: 2847,
    peakAccel: 6.12,
    peakGyro: 3.88,
    severity: 14.8,
    status: 'NOT TOO SEVERE',
    headline: 'LOW IMPACT',
  },
  moderate: {
    color: '#d97706',
    duration: 4120,
    peakAccel: 14.55,
    peakGyro: 9.21,
    severity: 48.6,
    status: 'MONITOR & EVALUATE',
    headline: 'MODERATE IMPACT',
  },
  high: {
    color: '#dc2626',
    duration: 5231,
    peakAccel: 22.4,
    peakGyro: 15.67,
    severity: 86.3,
    status: 'TAKE ACTION',
    headline: 'HIGH IMPACT',
  },
};
